apiVersion: apps/v1
kind: Deployment
metadata:
  name: sui-deployment
  labels:
    app: sui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sui
  template:
    metadata:
      labels:
        app: sui
    spec:
      containers:
      - name: sui
        image: igor04091968/sui:latest
        imagePullPolicy: Never # Важно: заставляет Kubernetes использовать локальный образ
        ports:
        - containerPort: 2095
---
apiVersion: v1
kind: Service
metadata:
  name: sui-service
spec:
  type: NodePort # Открывает доступ к приложению извне кластера
  selector:
    app: sui # Должен совпадать с 'labels' в Deployment
  ports:
    - protocol: TCP
      port: 2095
      targetPort: 2095
